apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- hpa.yaml

namespace: automation-laravel

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: automation-laravel
- patch: |-
    - op: replace
      path: /data/APP_ENV
      value: production
    - op: replace
      path: /data/APP_DEBUG
      value: "false"
    - op: replace
      path: /data/LOG_LEVEL
      value: warning
  target:
    kind: ConfigMap
    name: automation-config

images:
- name: ghcr.io/liberusoftware/automation-laravel
  newTag: latest
