apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automation-storage
  namespace: automation-laravel
  labels:
    app: automation-laravel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
