apiVersion: v1
kind: Service
metadata:
  name: automation-laravel
  namespace: automation-laravel
  labels:
    app: automation-laravel
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: automation-laravel
    component: application
